jeroen/curl

R/handle.R
tests/testthat/test-handle.R

A package I maintain (https://github.com/Crunch-io/rcrunch) depends on httr, and in checking it against the pre-release version of httr that depends on curl, I found that the new httr was largely a drop-in replacement, except for a ton of "Unknown options." errors. The error message in `handle_setopt` was not very helpful in debugging, so I modified it to identify the problem option(s). That allowed me to resolve the issues quickly.
The added tests show the validation erroring correctly when there are one or many invalid options, as well as confirming that it succeeds when the option is valid.

Tell me which options are invalid

---

src/curl.c

I don't know if I've done this correctly, but this modification seems to result in a working build of the curl package on OpenBSD. BSWAP_32 isn't defined, and is instead called swap32 on OpenBSD. I'm guessing there may be similar issues on FreeBSD and NetBSD as well (see the following for examples of how people have defined BSWAP_32 for those platforms):
https://github.com/jasperla/openbsd-wip/blob/master/x11/tde/k3b/patches/patch-libk3b_core_k3bglobals_cpp
Cheers,
Peter

Installation fails on OpenBSD due to undefined BSWAP_32

---

R/escape.R
tests/testthat/test-escape.R

This copies the default behavior of `RCurl`, which automatically coerces the
`url` argument to a character. This has the side-effect of fixing `NULL`
handling (see hadley/bigrquery#54 and hadley/httr#259).
If the goal was to explicitly *avoid* coercion (since the functions are
documented as consuming a character vector), I can reduce this to simply do
better `NULL` handling.
PTAL @jeroenooms

Coerce curl_escape/curl_unescape arguments to character.

---

src/nslookup.c

That broke at least OpenBSD 5.9 where neither `netdb.h` nor `arpa/inet.h` include `sys/socket.h`.

include sys/socket.h on non-win32 which is required for AF_INET/AF_INET6

---

src/callbacks.c
src/curl-common.h
src/fetch.c
src/interrupt.c
src/utils.c

As proposed in https://github.com/jeroenooms/curl/issues/25: catch `SIGINT` via multi-handle rather than in one of the callback functions. 
The `curl_perform_with_interrupt` function is a drop-in replacement for `curl_easy_perform` which returns `CURLE_ABORTED_BY_CALLBACK` when the R user has interrupted.
Need to properly test this on all platforms for side effects and performance regression.

Better user interruption

---

tests/testthat/test-handle.R

Here's a simplified test that connections are kept alive following https://github.com/jeroenooms/curl/commit/2184c23132a2ef631996630ac0172b3cbfa9958f. This test fails against previous master (release 2.2) but passes now (https://travis-ci.org/nealrichardson/curl/builds/175340444).

Test for keep-alive (#79)

---

src/curl.c

A bunch of test cases fail for me, but they also fail before this change, so I guess it is fine. I am not sure how we could test it.

Fix busy waiting in curl() open(), closes #84

---

revdep/problems.md
src/curl.c
tests/testthat/test-blockopen.R

This allows to `open()` a connection without blocking the opening itself by setting an `s` in the mode.
It passes the test cases by @gaborcsardi though the state of `con` after the error is undefined.
```r
library(curl)
con <- curl("http://httpbin.org/delay/10")
open(con, "rs", blocking = FALSE)
readLines(con)
while (isIncomplete(con)) {
Sys.sleep(0.1)
readLines(con)
}
library(curl)
con <- curl("http://httpbin.org/status/401")
open(con, "rs", blocking = FALSE)
readLines(con)
while (isIncomplete(con)) {
Sys.sleep(0.1)
readLines(con)
}
con <- curl("http://this.is.invalid.co.nz")
open(con, "rs", blocking = FALSE)
readLines(con)
while (isIncomplete(con)) {
Sys.sleep(0.1)
readLines(con)
}
con <- curl("http://240.0.0.1")
open(con, "rs", blocking = FALSE)
readLines(con)
while (isIncomplete(con)) …
```

Open connections in nonblocking

---

src/curl.c
tests/testthat/test-blockopen.R

@gaborcsardi would you be OK with this change?
The idea is that when performing a non-blocking `open()`, we do **not** raise an error for non-200 status code. This is to support use cases like https://github.com/jeroen/curl/issues/47 where the client wants to read the response text, even in case of an http error (e.g. a 400 error message). I think this makes sense.
So this means that when you open the connection as non blocking with the `s` parameter, you need to manually check the response status using `handle_data()`.

do not raise status-error when opened as non-blocking

---

src/handle.c

as documented here:
https://curl.haxx.se/libcurl/c/CURLOPT_HTTP200ALIASES.html
Otherwise, attempting to use this option causes a segfault because `curl_easy_setopt`
is being called with an R CHARSXP for the third parameter.

add CURLOPT_HTTP200ALIASES to set of curl_slist-requiring options

---

R/download.R
R/fetch.R
R/form.R
R/writer.R
tests/testthat/test-path.R

Fixes #182
If you are on board, I can add a test and apply the same `enc2native()` fix to other locations where it's needed.
This fixes the reprex I posted in #182 and, when curl is installed from this PR, fixes https://github.com/tidyverse/googledrive/issues/229.
``` r
library(curl)
destdir <- tempfile()
dir.create(destdir)
setwd(destdir)
res <- curl_fetch_disk("http://httpbin.org/stream/10", "äggplanta")
res$content
#> [1] "C:\\Users\\jenny\\AppData\\Local\\Temp\\RtmpSy9Rxd\\file27e87c9030d9\\äggplanta"
file.exists(res$content)
#> [1] TRUE
list.files()
#> [1] "äggplanta"
```
<sup>Created on 2019-04-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Make sure path has native encoding

---

configure

I've just added the shebang notation in the configure file to avoid build errors when running Docker's Buildx multiarch builds in Alpine-based images. Unfortunately, this happens in every shell script file that doesn't provide this notation.
Thanks for the amazing package :)

Adding shebang support

---

tests/testthat/test-echo.R

There is use of `webutils` without checking for it in the `test-echo.R` test. This adds a skip.

[ENH] skip test if no `webutils`

---

DESCRIPTION
NEWS
src/curl.c

Fix #329: in the streaming or non-blocking case, have `rcurl_read()` return any buffered bytes immediately before attempting to fetch more from the remote server. This way, even if the subsequent fetch fails due to the server closing the connection, the application has access to the bytes already sent by the server and buffered inside the R client's C code.

Fix #329: make rcurl_read() return without waiting if non-blocking

---

src/handle.c

Resolves #260 and perhaps r-lib/httr#626

Default to CURLOPT_UNRESTRICTED_AUTH = 0

---

NEWS
R/handle.R
tests/testthat/test-handle.R

Fixes https://github.com/r-lib/httr2/issues/428

Enable sending blank request headers

---

R/multi.R
src/curl.c
src/multi.c
tests/testthat/test-connection.R

Hi Jeroen,
This PR provides minimal changes so that packages such as `elmer` can continue using curl connections for streaming whilst adopting event-driven async using `later::later_fd()`, which efficiently polls sockets returned by `curl::multi_fdset()`.
It is a prerequisite for https://github.com/tidyverse/elmer/pull/158.
You'll be familiar with the issue facing us, summarized below:
1. `curl::curl()` returns an R connection object which does not contain any reference to the underlying C `struct Rconn` (RConnection).
2. The R connection object does have an external pointer as attribute 'conn_id', but this contains the address to an integer _pointer_, from which we cannot get the `struct Rconn` address.
3. As the curl CURLM handle is stored in the `struct Rconn`, this remains …

Support event-driven streaming async using curl connections

---

src/curl-common.h

Explicitly compare 'x' to NULL in make_string() macro

---

DESCRIPTION
NEWS
src/curl.c
src/utils.c

This is a nicer experience in interactive mode, however when running in non-interactive scripts (particularly CI jobs) I think it may still be better to raise an error, such that the log files clearly show that the job was interrupted. 
Update: apparently `R_Interactive` is also a "non-api" call so we don't differentiate between non/interactive mode.
Fixes #363. Fixes #271. Closes #364.

Re-throw interrupts

---

DESCRIPTION
NEWS
src/multi.c

Make sure to always call perform one more time, even after all results have been completed. Fixes https://github.com/jeroen/curl/issues/386

Fix for change in behavior of libcurl 8.12

---

src/callbacks.c

See https://github.com/r-lib/vctrs/pull/1968 for more discussion

Avoid memcpy of invalid pointer
